export default [
  {
    id: 1,
    clientName: "Boldbold Batbold",
    serviceName: "Hair Styling",
    price: 15000,
    date: "2025-05-15",
    time: "13:00",
    status: "pending",
    stylist: "Munkhbayar T.",
  },
  {
    id: 2,
    clientName: "Tsetsgee Oyungerel",
    serviceName: "Makeup",
    price: 30000,
    date: "2025-05-15",
    time: "15:00",
    status: "completed",
    stylist: "Enkhtuya B.",
  },
  {
    id: 3,
    clientName: "Sarnai Erdene",
    serviceName: "Manicure",
    price: 20000,
    date: "2025-05-16",
    time: "10:30",
    status: "completed",
    stylist: "Suren D.",
  },
  {
    id: 4,
    clientName: "Bat-Erdene Tuvshin",
    serviceName: "Haircut",
    price: 10000,
    date: "2025-05-16",
    time: "12:00",
    status: "pending",
    stylist: "Munkhbayar T.",
  },
  {
    id: 5,
    clientName: "Anu Bayarmaa",
    serviceName: "Facial Treatment",
    price: 35000,
    date: "2025-05-17",
    time: "14:00",
    status: "cancelled",
    stylist: "Enkhtuya B.",
  },
  {
    id: 6,
    clientName: "Dulguun Altangerel",
    serviceName: "Pedicure",
    price: 25000,
    date: "2025-05-17",
    time: "16:30",
    status: "pending",
    stylist: "Suren D.",
  },
  {
    id: 7,
    clientName: "Khulan Gantulga",
    serviceName: "Hair Coloring",
    price: 40000,
    date: "2025-05-18",
    time: "11:00",
    status: "completed",
    stylist: "Munkhbayar T.",
  },
  {
    id: 8,
    clientName: "Temuulen Bayasgalan",
    serviceName: "Makeup",
    price: 30000,
    date: "2025-05-18",
    time: "13:30",
    status: "pending",
    stylist: "Enkhtuya B.",
  },
  {
    id: 9,
    clientName: "Oyunbileg Sukhbaatar",
    serviceName: "Hair Styling",
    price: 15000,
    date: "2025-05-19",
    time: "09:00",
    status: "pending",
    stylist: "Munkhbayar T.",
  },
  {
    id: 10,
    clientName: "Bilguun Enkhbold",
    serviceName: "Manicure",
    price: 20000,
    date: "2025-05-19",
    time: "11:30",
    status: "completed",
    stylist: "Suren D.",
  },
  {
    id: 11,
    clientName: "Nomin-Erdene Tseren",
    serviceName: "Haircut",
    price: 10000,
    date: "2025-05-19",
    time: "14:00",
    status: "pending",
    stylist: "Munkhbayar T.",
  },
  {
    id: 12,
    clientName: "Erdenechimeg Lkhagva",
    serviceName: "Facial Treatment",
    price: 35000,
    date: "2025-05-20",
    time: "10:00",
    status: "pending",
    stylist: "Enkhtuya B.",
  },
  {
    id: 13,
    clientName: "Tuguldur Ganbold",
    serviceName: "Pedicure",
    price: 25000,
    date: "2025-05-20",
    time: "12:30",
    status: "pending",
    stylist: "Suren D.",
  },
  {
    id: 14,
    clientName: "Munkhzul Dorj",
    serviceName: "Hair Coloring",
    price: 40000,
    date: "2025-05-20",
    time: "15:00",
    status: "cancelled",
    stylist: "Munkhbayar T.",
  },
  {
    id: 15,
    clientName: "Soyolmaa Batmunkh",
    serviceName: "Makeup",
    price: 30000,
    date: "2025-05-21",
    time: "11:00",
    status: "pending",
    stylist: "Enkhtuya B.",
  },
  {
    id: 16,
    clientName: "Batzorig Tumen",
    serviceName: "Hair Styling",
    price: 15000,
    date: "2025-05-21",
    time: "13:30",
    status: "pending",
    stylist: "Munkhbayar T.",
  },
  {
    id: 17,
    clientName: "Ulziisaikhan Jargal",
    serviceName: "Manicure",
    price: 20000,
    date: "2025-05-21",
    time: "16:00",
    status: "completed",
    stylist: "Suren D.",
  },
  {
    id: 18,
    clientName: "Amarjargal Otgon",
    serviceName: "Haircut",
    price: 10000,
    date: "2025-05-22",
    time: "10:30",
    status: "pending",
    stylist: "Munkhbayar T.",
  },
  {
    id: 19,
    clientName: "Chuluun Enkh-Amgalan",
    serviceName: "Facial Treatment",
    price: 35000,
    date: "2025-05-22",
    time: "12:00",
    status: "pending",
    stylist: "Enkhtuya B.",
  },
  {
    id: 20,
    clientName: "Bayarmaa Tsend",
    serviceName: "Pedicure",
    price: 25000,
    date: "2025-05-22",
    time: "14:30",
    status: "completed",
    stylist: "Suren D.",
  },
];
